/****** Script for SelectTopNRows command from SSMS  ******/
SELECT  DISTINCT [record_id]
      ,[cmpy_code]
      ,[res_year]
      ,[res_period]
      ,[tch_code]
      ,[tch_name]
      ,[tch_init]
      ,[emp_code]
      ,[tud1_flg]
      ,[tud2_flg]
      ,[tud3_flg]
      ,[tud4_flg]
      ,[tud5_flg]
      ,[tud6_flg]
      ,[tud7_flg]
      ,[tud8_flg]
      ,[tud9_flg]
      ,[tud10_flg]
      ,[tud11_code]
      ,[tud12_code]
      ,[tud13_code]
      ,[tud14_code]
      ,[tud15_code]
      ,[tud16_code]
      ,[tud17_code]
      ,[tud18_code]
      ,[tud19_code]
      ,[tud20_code]
      ,[tud21_text]
      ,[tud22_text]
      ,[tud23_text]
      ,[tud24_text]
      ,[tud25_text]
      ,[surname]
      ,[curr_flg]
      ,[spell_chk_flg]
      ,[web_access_flg]
      ,[web_password]
      ,[e_mail]
      ,[pctut_grp]
      ,[update_by]
      ,[update_on]
      ,[substitute_flg]
      ,[rego_id]
      ,[sms_flg]
  FROM [tass].[dbo].[srateacher]
WHERE ([cmpy_code]= '01' OR [cmpy_code]= '02' OR [cmpy_code]= '03' OR [cmpy_code]= '04'  )
ORDER BY cmpy_code ASC;